kind: project
metadata:
  name: tensorflow-mlrun-knoldus
  created: '2024-03-06T08:39:22.827056'
spec:
  description: my new project
  functions:
  - url: /home/knoldus/Desktop/MLrun/src/pipeline/transformers_pipeline.py
    name: runner
    kind: job
    image: mlrun/mlrun
  - url: /home/knoldus/Desktop/MLrun/src/pipeline/transformers_pipeline.py
    name: new-runner
    kind: job
    image: mlrun/mlrun
  workflows: []
  artifacts: []
  conda: ''
  source: ''
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
